/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TorneiosIndexRouteImport } from './routes/torneios.index'
import { Route as RankingIndexRouteImport } from './routes/ranking.index'
import { Route as PartidasIndexRouteImport } from './routes/partidas.index'
import { Route as PartidasNovaRouteImport } from './routes/partidas.nova'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneiosIndexRoute = TorneiosIndexRouteImport.update({
  id: '/torneios/',
  path: '/torneios/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingIndexRoute = RankingIndexRouteImport.update({
  id: '/ranking/',
  path: '/ranking/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidasIndexRoute = PartidasIndexRouteImport.update({
  id: '/partidas/',
  path: '/partidas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidasNovaRoute = PartidasNovaRouteImport.update({
  id: '/partidas/nova',
  path: '/partidas/nova',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/partidas/nova': typeof PartidasNovaRoute
  '/partidas/': typeof PartidasIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/torneios/': typeof TorneiosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/partidas/nova': typeof PartidasNovaRoute
  '/partidas': typeof PartidasIndexRoute
  '/ranking': typeof RankingIndexRoute
  '/torneios': typeof TorneiosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/partidas/nova': typeof PartidasNovaRoute
  '/partidas/': typeof PartidasIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/torneios/': typeof TorneiosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/partidas/nova'
    | '/partidas/'
    | '/ranking/'
    | '/torneios/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/partidas/nova' | '/partidas' | '/ranking' | '/torneios'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/partidas/nova'
    | '/partidas/'
    | '/ranking/'
    | '/torneios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PartidasNovaRoute: typeof PartidasNovaRoute
  PartidasIndexRoute: typeof PartidasIndexRoute
  RankingIndexRoute: typeof RankingIndexRoute
  TorneiosIndexRoute: typeof TorneiosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneios/': {
      id: '/torneios/'
      path: '/torneios'
      fullPath: '/torneios/'
      preLoaderRoute: typeof TorneiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/': {
      id: '/ranking/'
      path: '/ranking'
      fullPath: '/ranking/'
      preLoaderRoute: typeof RankingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidas/': {
      id: '/partidas/'
      path: '/partidas'
      fullPath: '/partidas/'
      preLoaderRoute: typeof PartidasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidas/nova': {
      id: '/partidas/nova'
      path: '/partidas/nova'
      fullPath: '/partidas/nova'
      preLoaderRoute: typeof PartidasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PartidasNovaRoute: PartidasNovaRoute,
  PartidasIndexRoute: PartidasIndexRoute,
  RankingIndexRoute: RankingIndexRoute,
  TorneiosIndexRoute: TorneiosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
