/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as H2hRouteImport } from './routes/h2h'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TorneiosIndexRouteImport } from './routes/torneios.index'
import { Route as RegrasIndexRouteImport } from './routes/regras.index'
import { Route as PerfilIndexRouteImport } from './routes/perfil.index'
import { Route as PartidasIndexRouteImport } from './routes/partidas.index'
import { Route as ArenasIndexRouteImport } from './routes/arenas.index'
import { Route as AgendaIndexRouteImport } from './routes/agenda.index'
import { Route as TorneiosNovoRouteImport } from './routes/torneios.novo'
import { Route as TorneiosIdRouteImport } from './routes/torneios.$id'
import { Route as PerfilUsernameRouteImport } from './routes/perfil.$username'
import { Route as PartidasNovaRouteImport } from './routes/partidas.nova'
import { Route as ArenasIdRouteImport } from './routes/arenas.$id'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedRankingIndexRouteImport } from './routes/_authenticated/ranking.index'
import { Route as AuthenticatedDesafiosIndexRouteImport } from './routes/_authenticated/desafios.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminRelatoriosRouteImport } from './routes/_authenticated/admin/relatorios'
import { Route as AuthenticatedAdminNotificacoesRouteImport } from './routes/_authenticated/admin/notificacoes'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin/banners'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin/auditoria'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const H2hRoute = H2hRouteImport.update({
  id: '/h2h',
  path: '/h2h',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneiosIndexRoute = TorneiosIndexRouteImport.update({
  id: '/torneios/',
  path: '/torneios/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasIndexRoute = RegrasIndexRouteImport.update({
  id: '/regras/',
  path: '/regras/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidasIndexRoute = PartidasIndexRouteImport.update({
  id: '/partidas/',
  path: '/partidas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenasIndexRoute = ArenasIndexRouteImport.update({
  id: '/arenas/',
  path: '/arenas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaIndexRoute = AgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneiosNovoRoute = TorneiosNovoRouteImport.update({
  id: '/torneios/novo',
  path: '/torneios/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneiosIdRoute = TorneiosIdRouteImport.update({
  id: '/torneios/$id',
  path: '/torneios/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilUsernameRoute = PerfilUsernameRouteImport.update({
  id: '/perfil/$username',
  path: '/perfil/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidasNovaRoute = PartidasNovaRouteImport.update({
  id: '/partidas/nova',
  path: '/partidas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenasIdRoute = ArenasIdRouteImport.update({
  id: '/arenas/$id',
  path: '/arenas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingIndexRoute =
  AuthenticatedRankingIndexRouteImport.update({
    id: '/ranking/',
    path: '/ranking/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDesafiosIndexRoute =
  AuthenticatedDesafiosIndexRouteImport.update({
    id: '/desafios/',
    path: '/desafios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRelatoriosRoute =
  AuthenticatedAdminRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificacoesRoute =
  AuthenticatedAdminNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/h2h': typeof H2hRoute
  '/index': typeof Char91indexChar93Route
  '/notificacoes': typeof NotificacoesRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/arenas/$id': typeof ArenasIdRoute
  '/partidas/nova': typeof PartidasNovaRoute
  '/perfil/$username': typeof PerfilUsernameRoute
  '/torneios/$id': typeof TorneiosIdRoute
  '/torneios/novo': typeof TorneiosNovoRoute
  '/agenda/': typeof AgendaIndexRoute
  '/arenas/': typeof ArenasIndexRoute
  '/partidas/': typeof PartidasIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/regras/': typeof RegrasIndexRoute
  '/torneios/': typeof TorneiosIndexRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/desafios/': typeof AuthenticatedDesafiosIndexRoute
  '/ranking/': typeof AuthenticatedRankingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/h2h': typeof H2hRoute
  '/index': typeof Char91indexChar93Route
  '/notificacoes': typeof NotificacoesRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/arenas/$id': typeof ArenasIdRoute
  '/partidas/nova': typeof PartidasNovaRoute
  '/perfil/$username': typeof PerfilUsernameRoute
  '/torneios/$id': typeof TorneiosIdRoute
  '/torneios/novo': typeof TorneiosNovoRoute
  '/agenda': typeof AgendaIndexRoute
  '/arenas': typeof ArenasIndexRoute
  '/partidas': typeof PartidasIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/regras': typeof RegrasIndexRoute
  '/torneios': typeof TorneiosIndexRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/desafios': typeof AuthenticatedDesafiosIndexRoute
  '/ranking': typeof AuthenticatedRankingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/h2h': typeof H2hRoute
  '/index': typeof Char91indexChar93Route
  '/notificacoes': typeof NotificacoesRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/arenas/$id': typeof ArenasIdRoute
  '/partidas/nova': typeof PartidasNovaRoute
  '/perfil/$username': typeof PerfilUsernameRoute
  '/torneios/$id': typeof TorneiosIdRoute
  '/torneios/novo': typeof TorneiosNovoRoute
  '/agenda/': typeof AgendaIndexRoute
  '/arenas/': typeof ArenasIndexRoute
  '/partidas/': typeof PartidasIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/regras/': typeof RegrasIndexRoute
  '/torneios/': typeof TorneiosIndexRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/_authenticated/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/desafios/': typeof AuthenticatedDesafiosIndexRoute
  '/_authenticated/ranking/': typeof AuthenticatedRankingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/h2h'
    | '/index'
    | '/notificacoes'
    | '/redefinir-senha'
    | '/admin'
    | '/arenas/$id'
    | '/partidas/nova'
    | '/perfil/$username'
    | '/torneios/$id'
    | '/torneios/novo'
    | '/agenda/'
    | '/arenas/'
    | '/partidas/'
    | '/perfil/'
    | '/regras/'
    | '/torneios/'
    | '/admin/auditoria'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/notificacoes'
    | '/admin/relatorios'
    | '/admin/reports'
    | '/admin/usuarios'
    | '/admin/'
    | '/desafios/'
    | '/ranking/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/h2h'
    | '/index'
    | '/notificacoes'
    | '/redefinir-senha'
    | '/arenas/$id'
    | '/partidas/nova'
    | '/perfil/$username'
    | '/torneios/$id'
    | '/torneios/novo'
    | '/agenda'
    | '/arenas'
    | '/partidas'
    | '/perfil'
    | '/regras'
    | '/torneios'
    | '/admin/auditoria'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/notificacoes'
    | '/admin/relatorios'
    | '/admin/reports'
    | '/admin/usuarios'
    | '/admin'
    | '/desafios'
    | '/ranking'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/h2h'
    | '/index'
    | '/notificacoes'
    | '/redefinir-senha'
    | '/_authenticated/admin'
    | '/arenas/$id'
    | '/partidas/nova'
    | '/perfil/$username'
    | '/torneios/$id'
    | '/torneios/novo'
    | '/agenda/'
    | '/arenas/'
    | '/partidas/'
    | '/perfil/'
    | '/regras/'
    | '/torneios/'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/notificacoes'
    | '/_authenticated/admin/relatorios'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
    | '/_authenticated/desafios/'
    | '/_authenticated/ranking/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  H2hRoute: typeof H2hRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
  NotificacoesRoute: typeof NotificacoesRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  ArenasIdRoute: typeof ArenasIdRoute
  PartidasNovaRoute: typeof PartidasNovaRoute
  PerfilUsernameRoute: typeof PerfilUsernameRoute
  TorneiosIdRoute: typeof TorneiosIdRoute
  TorneiosNovoRoute: typeof TorneiosNovoRoute
  AgendaIndexRoute: typeof AgendaIndexRoute
  ArenasIndexRoute: typeof ArenasIndexRoute
  PartidasIndexRoute: typeof PartidasIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  RegrasIndexRoute: typeof RegrasIndexRoute
  TorneiosIndexRoute: typeof TorneiosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h2h': {
      id: '/h2h'
      path: '/h2h'
      fullPath: '/h2h'
      preLoaderRoute: typeof H2hRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneios/': {
      id: '/torneios/'
      path: '/torneios'
      fullPath: '/torneios/'
      preLoaderRoute: typeof TorneiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras/': {
      id: '/regras/'
      path: '/regras'
      fullPath: '/regras/'
      preLoaderRoute: typeof RegrasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidas/': {
      id: '/partidas/'
      path: '/partidas'
      fullPath: '/partidas/'
      preLoaderRoute: typeof PartidasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arenas/': {
      id: '/arenas/'
      path: '/arenas'
      fullPath: '/arenas/'
      preLoaderRoute: typeof ArenasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/': {
      id: '/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AgendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneios/novo': {
      id: '/torneios/novo'
      path: '/torneios/novo'
      fullPath: '/torneios/novo'
      preLoaderRoute: typeof TorneiosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneios/$id': {
      id: '/torneios/$id'
      path: '/torneios/$id'
      fullPath: '/torneios/$id'
      preLoaderRoute: typeof TorneiosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$username': {
      id: '/perfil/$username'
      path: '/perfil/$username'
      fullPath: '/perfil/$username'
      preLoaderRoute: typeof PerfilUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidas/nova': {
      id: '/partidas/nova'
      path: '/partidas/nova'
      fullPath: '/partidas/nova'
      preLoaderRoute: typeof PartidasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arenas/$id': {
      id: '/arenas/$id'
      path: '/arenas/$id'
      fullPath: '/arenas/$id'
      preLoaderRoute: typeof ArenasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking/': {
      id: '/_authenticated/ranking/'
      path: '/ranking'
      fullPath: '/ranking/'
      preLoaderRoute: typeof AuthenticatedRankingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desafios/': {
      id: '/_authenticated/desafios/'
      path: '/desafios'
      fullPath: '/desafios/'
      preLoaderRoute: typeof AuthenticatedDesafiosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/relatorios': {
      id: '/_authenticated/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notificacoes': {
      id: '/_authenticated/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AuthenticatedAdminNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminNotificacoesRoute: typeof AuthenticatedAdminNotificacoesRoute
  AuthenticatedAdminRelatoriosRoute: typeof AuthenticatedAdminRelatoriosRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
    AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminNotificacoesRoute: AuthenticatedAdminNotificacoesRoute,
    AuthenticatedAdminRelatoriosRoute: AuthenticatedAdminRelatoriosRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDesafiosIndexRoute: typeof AuthenticatedDesafiosIndexRoute
  AuthenticatedRankingIndexRoute: typeof AuthenticatedRankingIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDesafiosIndexRoute: AuthenticatedDesafiosIndexRoute,
  AuthenticatedRankingIndexRoute: AuthenticatedRankingIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  H2hRoute: H2hRoute,
  Char91indexChar93Route: Char91indexChar93Route,
  NotificacoesRoute: NotificacoesRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  ArenasIdRoute: ArenasIdRoute,
  PartidasNovaRoute: PartidasNovaRoute,
  PerfilUsernameRoute: PerfilUsernameRoute,
  TorneiosIdRoute: TorneiosIdRoute,
  TorneiosNovoRoute: TorneiosNovoRoute,
  AgendaIndexRoute: AgendaIndexRoute,
  ArenasIndexRoute: ArenasIndexRoute,
  PartidasIndexRoute: PartidasIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  RegrasIndexRoute: RegrasIndexRoute,
  TorneiosIndexRoute: TorneiosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
