/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as H2hRouteImport } from './routes/h2h'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TorneiosIndexRouteImport } from './routes/torneios.index'
import { Route as RankingIndexRouteImport } from './routes/ranking.index'
import { Route as PerfilIndexRouteImport } from './routes/perfil.index'
import { Route as PartidasIndexRouteImport } from './routes/partidas.index'
import { Route as DesafiosIndexRouteImport } from './routes/desafios.index'
import { Route as ArenasIndexRouteImport } from './routes/arenas.index'
import { Route as AgendaIndexRouteImport } from './routes/agenda.index'
import { Route as TorneiosIdRouteImport } from './routes/torneios.$id'
import { Route as PartidasNovaRouteImport } from './routes/partidas.nova'
import { Route as ArenasIdRouteImport } from './routes/arenas.$id'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminRelatoriosRouteImport } from './routes/_authenticated/admin/relatorios'
import { Route as AuthenticatedAdminNotificacoesRouteImport } from './routes/_authenticated/admin/notificacoes'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin/banners'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin/auditoria'

const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const H2hRoute = H2hRouteImport.update({
  id: '/h2h',
  path: '/h2h',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneiosIndexRoute = TorneiosIndexRouteImport.update({
  id: '/torneios/',
  path: '/torneios/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingIndexRoute = RankingIndexRouteImport.update({
  id: '/ranking/',
  path: '/ranking/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidasIndexRoute = PartidasIndexRouteImport.update({
  id: '/partidas/',
  path: '/partidas/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosIndexRoute = DesafiosIndexRouteImport.update({
  id: '/desafios/',
  path: '/desafios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenasIndexRoute = ArenasIndexRouteImport.update({
  id: '/arenas/',
  path: '/arenas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaIndexRoute = AgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneiosIdRoute = TorneiosIdRouteImport.update({
  id: '/torneios/$id',
  path: '/torneios/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidasNovaRoute = PartidasNovaRouteImport.update({
  id: '/partidas/nova',
  path: '/partidas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenasIdRoute = ArenasIdRouteImport.update({
  id: '/arenas/$id',
  path: '/arenas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRelatoriosRoute =
  AuthenticatedAdminRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificacoesRoute =
  AuthenticatedAdminNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/h2h': typeof H2hRoute
  '/notificacoes': typeof NotificacoesRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/arenas/$id': typeof ArenasIdRoute
  '/partidas/nova': typeof PartidasNovaRoute
  '/torneios/$id': typeof TorneiosIdRoute
  '/agenda/': typeof AgendaIndexRoute
  '/arenas/': typeof ArenasIndexRoute
  '/desafios/': typeof DesafiosIndexRoute
  '/partidas/': typeof PartidasIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/torneios/': typeof TorneiosIndexRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/h2h': typeof H2hRoute
  '/notificacoes': typeof NotificacoesRoute
  '/arenas/$id': typeof ArenasIdRoute
  '/partidas/nova': typeof PartidasNovaRoute
  '/torneios/$id': typeof TorneiosIdRoute
  '/agenda': typeof AgendaIndexRoute
  '/arenas': typeof ArenasIndexRoute
  '/desafios': typeof DesafiosIndexRoute
  '/partidas': typeof PartidasIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/ranking': typeof RankingIndexRoute
  '/torneios': typeof TorneiosIndexRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/h2h': typeof H2hRoute
  '/notificacoes': typeof NotificacoesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/arenas/$id': typeof ArenasIdRoute
  '/partidas/nova': typeof PartidasNovaRoute
  '/torneios/$id': typeof TorneiosIdRoute
  '/agenda/': typeof AgendaIndexRoute
  '/arenas/': typeof ArenasIndexRoute
  '/desafios/': typeof DesafiosIndexRoute
  '/partidas/': typeof PartidasIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/torneios/': typeof TorneiosIndexRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/_authenticated/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/h2h'
    | '/notificacoes'
    | '/admin'
    | '/arenas/$id'
    | '/partidas/nova'
    | '/torneios/$id'
    | '/agenda/'
    | '/arenas/'
    | '/desafios/'
    | '/partidas/'
    | '/perfil/'
    | '/ranking/'
    | '/torneios/'
    | '/admin/auditoria'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/notificacoes'
    | '/admin/relatorios'
    | '/admin/reports'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/h2h'
    | '/notificacoes'
    | '/arenas/$id'
    | '/partidas/nova'
    | '/torneios/$id'
    | '/agenda'
    | '/arenas'
    | '/desafios'
    | '/partidas'
    | '/perfil'
    | '/ranking'
    | '/torneios'
    | '/admin/auditoria'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/notificacoes'
    | '/admin/relatorios'
    | '/admin/reports'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/h2h'
    | '/notificacoes'
    | '/_authenticated/admin'
    | '/arenas/$id'
    | '/partidas/nova'
    | '/torneios/$id'
    | '/agenda/'
    | '/arenas/'
    | '/desafios/'
    | '/partidas/'
    | '/perfil/'
    | '/ranking/'
    | '/torneios/'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/notificacoes'
    | '/_authenticated/admin/relatorios'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  H2hRoute: typeof H2hRoute
  NotificacoesRoute: typeof NotificacoesRoute
  ArenasIdRoute: typeof ArenasIdRoute
  PartidasNovaRoute: typeof PartidasNovaRoute
  TorneiosIdRoute: typeof TorneiosIdRoute
  AgendaIndexRoute: typeof AgendaIndexRoute
  ArenasIndexRoute: typeof ArenasIndexRoute
  DesafiosIndexRoute: typeof DesafiosIndexRoute
  PartidasIndexRoute: typeof PartidasIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  RankingIndexRoute: typeof RankingIndexRoute
  TorneiosIndexRoute: typeof TorneiosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h2h': {
      id: '/h2h'
      path: '/h2h'
      fullPath: '/h2h'
      preLoaderRoute: typeof H2hRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneios/': {
      id: '/torneios/'
      path: '/torneios'
      fullPath: '/torneios/'
      preLoaderRoute: typeof TorneiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/': {
      id: '/ranking/'
      path: '/ranking'
      fullPath: '/ranking/'
      preLoaderRoute: typeof RankingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidas/': {
      id: '/partidas/'
      path: '/partidas'
      fullPath: '/partidas/'
      preLoaderRoute: typeof PartidasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios/': {
      id: '/desafios/'
      path: '/desafios'
      fullPath: '/desafios/'
      preLoaderRoute: typeof DesafiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arenas/': {
      id: '/arenas/'
      path: '/arenas'
      fullPath: '/arenas/'
      preLoaderRoute: typeof ArenasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/': {
      id: '/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AgendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneios/$id': {
      id: '/torneios/$id'
      path: '/torneios/$id'
      fullPath: '/torneios/$id'
      preLoaderRoute: typeof TorneiosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidas/nova': {
      id: '/partidas/nova'
      path: '/partidas/nova'
      fullPath: '/partidas/nova'
      preLoaderRoute: typeof PartidasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arenas/$id': {
      id: '/arenas/$id'
      path: '/arenas/$id'
      fullPath: '/arenas/$id'
      preLoaderRoute: typeof ArenasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/relatorios': {
      id: '/_authenticated/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notificacoes': {
      id: '/_authenticated/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AuthenticatedAdminNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminNotificacoesRoute: typeof AuthenticatedAdminNotificacoesRoute
  AuthenticatedAdminRelatoriosRoute: typeof AuthenticatedAdminRelatoriosRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
    AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminNotificacoesRoute: AuthenticatedAdminNotificacoesRoute,
    AuthenticatedAdminRelatoriosRoute: AuthenticatedAdminRelatoriosRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  H2hRoute: H2hRoute,
  NotificacoesRoute: NotificacoesRoute,
  ArenasIdRoute: ArenasIdRoute,
  PartidasNovaRoute: PartidasNovaRoute,
  TorneiosIdRoute: TorneiosIdRoute,
  AgendaIndexRoute: AgendaIndexRoute,
  ArenasIndexRoute: ArenasIndexRoute,
  DesafiosIndexRoute: DesafiosIndexRoute,
  PartidasIndexRoute: PartidasIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  RankingIndexRoute: RankingIndexRoute,
  TorneiosIndexRoute: TorneiosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
